/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PublishToBlogPlugin
});
module.exports = __toCommonJS(main_exports);
var import_child_process = require("child_process");
var import_obsidian2 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  blogFolderPath: "",
  autoSync: true,
  hexoRootPath: "",
  deployCommand: "hexo g -d",
  bufferMinutes: 5,
  autoDeploy: false
};
var PublishSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Publish to Blog Settings" });
    new import_obsidian.Setting(containerEl).setName("Blog folder path").setDesc("Absolute path to your blog posts folder (e.g. D:/my-blog/posts/)").addText(
      (text) => text.setPlaceholder("D:/my-blog/posts/").setValue(this.plugin.settings.blogFolderPath).onChange(async (value) => {
        this.plugin.settings.blogFolderPath = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto sync on save").setDesc("Automatically copy the note to the blog folder when a publish-marked file is saved.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
        this.plugin.settings.autoSync = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Deployment" });
    new import_obsidian.Setting(containerEl).setName("Auto deploy").setDesc("Automatically run the deploy command after a period of no changes.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoDeploy).onChange(async (value) => {
        this.plugin.settings.autoDeploy = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Hexo root path").setDesc("Absolute path to your Hexo project root (where _config.yml lives).").addText(
      (text) => text.setPlaceholder("D:/my-blog/").setValue(this.plugin.settings.hexoRootPath).onChange(async (value) => {
        this.plugin.settings.hexoRootPath = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Deploy command").setDesc("Command to build and deploy your blog (runs in Hexo root directory).").addText(
      (text) => text.setPlaceholder("hexo g -d").setValue(this.plugin.settings.deployCommand).onChange(async (value) => {
        this.plugin.settings.deployCommand = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Buffer time (minutes)").setDesc("Minutes to wait after the last change before auto-deploy fires.").addSlider(
      (slider) => slider.setLimits(1, 60, 1).setValue(this.plugin.settings.bufferMinutes).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.bufferMinutes = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var fs = __toESM(require("fs"));
var path = __toESM(require("path"));
var PublishToBlogPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.syncTimers = /* @__PURE__ */ new Map();
    this.deployTimer = null;
    this.isDeploying = false;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new PublishSettingTab(this.app, this));
    this.addCommand({
      id: "toggle-publish",
      name: "Toggle publish for current note",
      editorCheckCallback: (checking, _editor, ctx) => {
        const file = ctx.file;
        if (!(file instanceof import_obsidian2.TFile) || file.extension !== "md")
          return false;
        if (!checking) {
          this.togglePublish(file);
        }
        return true;
      }
    });
    this.addCommand({
      id: "sync-all-published",
      name: "Sync all published notes to blog",
      callback: () => this.syncAllPublished()
    });
    this.addCommand({
      id: "sync-current-file",
      name: "Sync current note to blog",
      callback: () => {
        const file = this.app.workspace.getActiveFile();
        if (file instanceof import_obsidian2.TFile && file.extension === "md") {
          this.syncSingleFile(file);
        } else {
          new import_obsidian2.Notice("No active markdown file to sync.");
        }
      }
    });
    this.addCommand({
      id: "deploy-now",
      name: "Deploy blog now",
      callback: () => {
        if (this.deployTimer) {
          clearTimeout(this.deployTimer);
          this.deployTimer = null;
        }
        this.runDeploy();
      }
    });
    this.addRibbonIcon("send", "Sync all published notes to blog", () => {
      this.syncAllPublished();
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian2.TFile) || file.extension !== "md")
          return;
        const published = this.isPublished(file);
        menu.addItem((item) => {
          item.setTitle(published ? "Unmark as publish" : "Mark as publish").setIcon(published ? "bookmark" : "bookmark-plus").onClick(() => this.togglePublish(file));
        });
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        this.debouncedAutoSync(file);
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian2.TFile) {
          this.debouncedAutoSync(file);
        }
      })
    );
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  isPublished(file) {
    var _a;
    const cache = this.app.metadataCache.getFileCache(file);
    const publish = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.publish;
    return publish === true;
  }
  async togglePublish(file) {
    const current = this.isPublished(file);
    const next = !current;
    await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      frontmatter["publish"] = next;
    });
    new import_obsidian2.Notice(`Marked as ${next ? "publish" : "private"}: ${file.basename}`);
    if (next && this.settings.autoSync) {
      this.syncSingleFile(file);
    }
  }
  debouncedAutoSync(file) {
    if (!this.settings.autoSync)
      return;
    if (!this.isPublished(file))
      return;
    const key = file.path;
    const existing = this.syncTimers.get(key);
    if (existing)
      clearTimeout(existing);
    this.syncTimers.set(
      key,
      setTimeout(() => {
        this.syncTimers.delete(key);
        this.syncSingleFile(file);
      }, 800)
    );
  }
  async syncSingleFile(file) {
    const blogPath = this.settings.blogFolderPath.trim();
    if (!blogPath) {
      new import_obsidian2.Notice("Blog folder path is not configured. Check plugin settings.");
      return;
    }
    try {
      const content = await this.app.vault.read(file);
      const targetPath = path.join(
        blogPath.replace(/[/\\]$/, ""),
        file.path
      );
      const targetDir = path.dirname(targetPath);
      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }
      fs.writeFileSync(targetPath, content, "utf-8");
      new import_obsidian2.Notice(`Synced to blog: ${file.path}`);
      if (this.settings.autoDeploy)
        this.resetDeployTimer();
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      new import_obsidian2.Notice(`Sync failed: ${file.basename}. ${msg}`);
      console.error("PublishToBlog sync error:", e);
    }
  }
  async syncAllPublished() {
    const blogPath = this.settings.blogFolderPath.trim();
    if (!blogPath) {
      new import_obsidian2.Notice("Blog folder path is not configured. Check plugin settings.");
      return;
    }
    const files = this.app.vault.getMarkdownFiles();
    let synced = 0;
    let errors = 0;
    for (const file of files) {
      if (this.isPublished(file)) {
        try {
          await this.syncSingleFile(file);
          synced++;
        } catch (e) {
          errors++;
        }
      }
    }
    new import_obsidian2.Notice(`Sync complete: ${synced} synced${errors > 0 ? `, ${errors} errors` : ""}`);
  }
  resetDeployTimer() {
    if (this.deployTimer)
      clearTimeout(this.deployTimer);
    this.deployTimer = setTimeout(() => {
      this.deployTimer = null;
      this.runDeploy();
    }, this.settings.bufferMinutes * 60 * 1e3);
  }
  runDeploy() {
    if (this.isDeploying) {
      console.log("PublishToBlog: Deploy already in progress, skipping.");
      return;
    }
    const hexoRoot = this.settings.hexoRootPath.trim();
    const cmd = this.settings.deployCommand.trim();
    if (!hexoRoot || !cmd) {
      new import_obsidian2.Notice("Hexo root path or deploy command not configured. Check plugin settings.");
      return;
    }
    if (!fs.existsSync(hexoRoot)) {
      new import_obsidian2.Notice(`Hexo root path does not exist: ${hexoRoot}`);
      return;
    }
    this.isDeploying = true;
    new import_obsidian2.Notice(`Deploy started: ${cmd}`);
    (0, import_child_process.exec)(cmd, { cwd: hexoRoot }, (error, stdout, stderr) => {
      this.isDeploying = false;
      if (error) {
        new import_obsidian2.Notice(`Deploy failed: ${error.message}`);
        console.error("PublishToBlog deploy error stdout:", stdout);
        console.error("PublishToBlog deploy error stderr:", stderr);
      } else {
        new import_obsidian2.Notice("Deploy completed successfully!");
        if (stdout)
          console.log("PublishToBlog deploy stdout:", stdout);
      }
    });
  }
  onunload() {
    this.syncTimers.forEach((t) => clearTimeout(t));
    this.syncTimers.clear();
    if (this.deployTimer)
      clearTimeout(this.deployTimer);
  }
};
