/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PublishToBlogPlugin
});
module.exports = __toCommonJS(main_exports);
var import_child_process = require("child_process");
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  blogFolderPath: "",
  autoSync: true,
  hexoRootPath: "",
  deployCommand: "hexo g -d",
  bufferMinutes: 5,
  autoDeploy: false
};
var PublishSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Publish to Blog Settings" });
    new import_obsidian.Setting(containerEl).setName("Blog folder path").setDesc("Absolute path to your blog posts folder (e.g. D:/my-blog/posts/)").addText(
      (text) => text.setPlaceholder("D:/my-blog/posts/").setValue(this.plugin.settings.blogFolderPath).onChange(async (value) => {
        this.plugin.settings.blogFolderPath = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto sync on save").setDesc("Automatically copy the note to the blog folder when a publish-marked file is saved.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
        this.plugin.settings.autoSync = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Deployment" });
    new import_obsidian.Setting(containerEl).setName("Auto deploy").setDesc("Automatically run the deploy command after a period of no changes.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoDeploy).onChange(async (value) => {
        this.plugin.settings.autoDeploy = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Hexo root path").setDesc("Absolute path to your Hexo project root (where _config.yml lives).").addText(
      (text) => text.setPlaceholder("D:/my-blog/").setValue(this.plugin.settings.hexoRootPath).onChange(async (value) => {
        this.plugin.settings.hexoRootPath = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Deploy command").setDesc("Command to build and deploy your blog (runs in Hexo root directory).").addText(
      (text) => text.setPlaceholder("hexo g -d").setValue(this.plugin.settings.deployCommand).onChange(async (value) => {
        this.plugin.settings.deployCommand = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Buffer time (minutes)").setDesc("Minutes to wait after the last change before auto-deploy fires.").addSlider(
      (slider) => slider.setLimits(1, 60, 1).setValue(this.plugin.settings.bufferMinutes).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.bufferMinutes = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/dashboard.ts
var import_obsidian3 = require("obsidian");

// src/hexo-utils.ts
var import_obsidian2 = require("obsidian");
var fs = __toESM(require("fs"));
var path = __toESM(require("path"));
function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match)
    return null;
  try {
    return (0, import_obsidian2.parseYaml)(match[1]) || {};
  } catch (e) {
    return null;
  }
}
function normalizeStringArray(value) {
  if (!value)
    return [];
  if (Array.isArray(value))
    return value.map((v) => String(v));
  if (typeof value === "string")
    return [value];
  if (typeof value === "object" && value !== null) {
    if (Array.isArray(value.map)) {
      return value.map.map((v) => String(v));
    }
    return [];
  }
  return [];
}
function scanPosts(blogFolderPath) {
  const postsDir = path.resolve(blogFolderPath);
  if (!fs.existsSync(postsDir))
    return [];
  const posts = [];
  function walk(dir) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.name.endsWith(".md")) {
        try {
          const content = fs.readFileSync(fullPath, "utf-8");
          const fm = parseFrontmatter(content);
          if (fm) {
            posts.push({
              title: fm.title || entry.name.replace(".md", ""),
              date: fm.date || "",
              categories: normalizeStringArray(fm.categories),
              tags: normalizeStringArray(fm.tags),
              filePath: path.relative(blogFolderPath, fullPath).replace(/\\/g, "/"),
              fileName: entry.name
            });
          }
        } catch (e) {
        }
      }
    }
  }
  walk(postsDir);
  posts.sort((a, b) => b.date.localeCompare(a.date));
  return posts;
}
function getBlogStats(blogFolderPath) {
  const posts = scanPosts(blogFolderPath);
  const categories = /* @__PURE__ */ new Set();
  const tags = /* @__PURE__ */ new Set();
  for (const post of posts) {
    for (const cat of post.categories)
      categories.add(cat);
    for (const tag of post.tags)
      tags.add(tag);
  }
  return {
    totalPosts: posts.length,
    totalCategories: categories.size,
    totalTags: tags.size
  };
}
function getCategoryList(blogFolderPath) {
  const posts = scanPosts(blogFolderPath);
  const map = /* @__PURE__ */ new Map();
  for (const post of posts) {
    for (const cat of post.categories) {
      map.set(cat, (map.get(cat) || 0) + 1);
    }
  }
  return [...map.entries()].map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count);
}
function getTagList(blogFolderPath) {
  const posts = scanPosts(blogFolderPath);
  const map = /* @__PURE__ */ new Map();
  for (const post of posts) {
    for (const tag of post.tags) {
      map.set(tag, (map.get(tag) || 0) + 1);
    }
  }
  return [...map.entries()].map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count);
}

// src/dashboard.ts
var fs2 = __toESM(require("fs"));
var VIEW_TYPE_DASHBOARD = "obsidian-to-blog-dashboard";
var DashboardView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_DASHBOARD;
  }
  getDisplayText() {
    return "Blog Dashboard";
  }
  getIcon() {
    return "bar-chart-2";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("blog-dashboard");
    const blogPath = this.plugin.settings.blogFolderPath.trim();
    if (!blogPath || !fs2.existsSync(blogPath)) {
      container.createEl("div", {
        cls: "blog-dashboard-empty",
        text: "Blog folder path not configured or does not exist.\nGo to plugin settings to configure."
      });
      return;
    }
    const stats = getBlogStats(blogPath);
    const recentPosts = scanPosts(blogPath).slice(0, 10);
    const categories = getCategoryList(blogPath);
    const tags = getTagList(blogPath);
    const header = container.createEl("div", { cls: "blog-dashboard-header" });
    header.createEl("h2", { text: "Blog Dashboard" });
    const refreshBtn = header.createEl("button", {
      cls: "blog-dashboard-refresh",
      text: "Refresh"
    });
    refreshBtn.addEventListener("click", () => this.render());
    const statsRow = container.createEl("div", { cls: "blog-stats-row" });
    this.createStatCard(statsRow, "Posts", String(stats.totalPosts));
    this.createStatCard(statsRow, "Categories", String(stats.totalCategories));
    this.createStatCard(statsRow, "Tags", String(stats.totalTags));
    const actions = container.createEl("div", { cls: "blog-actions" });
    actions.createEl("h4", { text: "Quick Actions" });
    const actionsRow = actions.createEl("div", { cls: "blog-actions-row" });
    this.createActionButton(actionsRow, "Generate & Deploy", () => {
      this.plugin.cancelDeployTimer();
      this.plugin.runDeploy();
    });
    this.createActionButton(actionsRow, "Sync All", () => {
      this.plugin.syncAllPublished();
    });
    const recentSection = container.createEl("div", {
      cls: "blog-section"
    });
    recentSection.createEl("h4", { text: "Recent Posts" });
    if (recentPosts.length === 0) {
      recentSection.createEl("div", {
        cls: "blog-empty-hint",
        text: "No posts found."
      });
    } else {
      const list = recentSection.createEl("div", { cls: "blog-post-list" });
      for (const post of recentPosts) {
        const item = list.createEl("div", { cls: "blog-post-item" });
        const meta = item.createEl("span", { cls: "blog-post-date" });
        meta.setText(post.date ? post.date.slice(0, 10) : "");
        item.createEl("span", { cls: "blog-post-title", text: post.title });
      }
    }
    const catSection = container.createEl("div", { cls: "blog-section" });
    catSection.createEl("h4", { text: "Categories" });
    if (categories.length === 0) {
      catSection.createEl("div", {
        cls: "blog-empty-hint",
        text: "No categories."
      });
    } else {
      this.renderCategoryTagList(catSection, categories, "category");
    }
    const tagSection = container.createEl("div", { cls: "blog-section" });
    tagSection.createEl("h4", { text: "Tags" });
    if (tags.length === 0) {
      tagSection.createEl("div", {
        cls: "blog-empty-hint",
        text: "No tags."
      });
    } else {
      this.renderCategoryTagList(tagSection, tags, "tag");
    }
  }
  createStatCard(parent, label, value) {
    const card = parent.createEl("div", { cls: "blog-stat-card" });
    card.createEl("div", { cls: "blog-stat-value", text: value });
    card.createEl("div", { cls: "blog-stat-label", text: label });
  }
  createActionButton(parent, text, onClick) {
    const btn = parent.createEl("button", { cls: "blog-action-btn", text });
    btn.addEventListener("click", onClick);
  }
  renderCategoryTagList(parent, items, type) {
    const container = parent.createEl("div", { cls: "blog-chips" });
    for (const item of items) {
      const chip = container.createEl("span", { cls: "blog-chip" });
      const icon = type === "category" ? "\u{1F4C2}" : "\u{1F3F7}";
      chip.setText(`${icon} ${item.name} (${item.count})`);
    }
  }
};

// src/metadata-modal.ts
var import_obsidian4 = require("obsidian");
var MetadataModal = class extends import_obsidian4.Modal {
  constructor(app, plugin, file) {
    var _a;
    super(app);
    this.plugin = plugin;
    this.file = file;
    const fm = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    this.existingTitle = (fm == null ? void 0 : fm.title) || "";
    this.existingCategories = normalizeArray(fm == null ? void 0 : fm.categories);
    this.existingTags = normalizeArray(fm == null ? void 0 : fm.tags);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("metadata-modal");
    contentEl.createEl("h2", { text: "Edit Post Metadata" });
    let titleValue = this.existingTitle;
    let categoriesValue = this.existingCategories.join(", ");
    let tagsValue = this.existingTags.join(", ");
    new import_obsidian4.Setting(contentEl).setName("Title").addText((text) => {
      text.setPlaceholder("Post title").setValue(titleValue).onChange((v) => titleValue = v);
      text.inputEl.style.width = "100%";
    });
    new import_obsidian4.Setting(contentEl).setName("Categories").setDesc("Comma-separated").addText((text) => {
      text.setPlaceholder("\u6280\u672F, \u524D\u7AEF").setValue(categoriesValue).onChange((v) => categoriesValue = v);
      text.inputEl.style.width = "100%";
    });
    new import_obsidian4.Setting(contentEl).setName("Tags").setDesc("Comma-separated").addText((text) => {
      text.setPlaceholder("javascript, tutorial").setValue(tagsValue).onChange((v) => tagsValue = v);
      text.inputEl.style.width = "100%";
    });
    const buttons = contentEl.createEl("div", { cls: "metadata-modal-buttons" });
    const cancelBtn = buttons.createEl("button", { text: "Cancel" });
    cancelBtn.addEventListener("click", () => this.close());
    const saveBtn = buttons.createEl("button", {
      cls: "mod-cta",
      text: "Save & Sync"
    });
    saveBtn.addEventListener("click", async () => {
      saveBtn.disabled = true;
      saveBtn.setText("Saving...");
      const newCategories = splitTrim(categoriesValue);
      const newTags = splitTrim(tagsValue);
      await this.app.fileManager.processFrontMatter(this.file, (fm) => {
        fm["title"] = titleValue.trim() || void 0;
        fm["categories"] = newCategories.length > 0 ? newCategories : void 0;
        fm["tags"] = newTags.length > 0 ? newTags : void 0;
      });
      this.plugin.syncSingleFile(this.file);
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
function normalizeArray(value) {
  if (!value)
    return [];
  if (Array.isArray(value))
    return value.map(String);
  if (typeof value === "string")
    return [value];
  return [];
}
function splitTrim(input) {
  return input.split(/[,，]/).map((s) => s.trim()).filter(Boolean);
}

// src/main.ts
var fs3 = __toESM(require("fs"));
var path2 = __toESM(require("path"));
var PublishToBlogPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.syncTimers = /* @__PURE__ */ new Map();
    this.deployTimer = null;
    this.isDeploying = false;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new PublishSettingTab(this.app, this));
    this.registerView(
      VIEW_TYPE_DASHBOARD,
      (leaf) => new DashboardView(leaf, this)
    );
    this.addCommand({
      id: "open-dashboard",
      name: "Open blog dashboard",
      callback: () => this.activateDashboard()
    });
    this.addCommand({
      id: "toggle-publish",
      name: "Toggle publish for current note",
      editorCheckCallback: (checking, _editor, ctx) => {
        const file = ctx.file;
        if (!(file instanceof import_obsidian5.TFile) || file.extension !== "md")
          return false;
        if (!checking) {
          this.togglePublish(file);
        }
        return true;
      }
    });
    this.addCommand({
      id: "sync-all-published",
      name: "Sync all published notes to blog",
      callback: () => this.syncAllPublished()
    });
    this.addCommand({
      id: "sync-current-file",
      name: "Sync current note to blog",
      callback: () => {
        const file = this.app.workspace.getActiveFile();
        if (file instanceof import_obsidian5.TFile && file.extension === "md") {
          this.syncSingleFile(file);
        } else {
          new import_obsidian5.Notice("No active markdown file to sync.");
        }
      }
    });
    this.addCommand({
      id: "deploy-now",
      name: "Deploy blog now",
      callback: () => {
        if (this.deployTimer) {
          clearTimeout(this.deployTimer);
          this.deployTimer = null;
        }
        this.runDeploy();
      }
    });
    this.addCommand({
      id: "edit-metadata",
      name: "Edit post metadata",
      editorCheckCallback: (checking, _editor, ctx) => {
        const file = ctx.file;
        if (!(file instanceof import_obsidian5.TFile) || file.extension !== "md")
          return false;
        if (!checking) {
          new MetadataModal(this.app, this, file).open();
        }
        return true;
      }
    });
    this.addRibbonIcon("send", "Sync all published notes to blog", () => {
      this.syncAllPublished();
    });
    this.addRibbonIcon("bar-chart-2", "Open blog dashboard", () => {
      this.activateDashboard();
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian5.TFile) || file.extension !== "md")
          return;
        const published = this.isPublished(file);
        menu.addItem((item) => {
          item.setTitle(published ? "Unmark as publish" : "Mark as publish").setIcon(published ? "bookmark" : "bookmark-plus").onClick(() => this.togglePublish(file));
        });
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        this.debouncedAutoSync(file);
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian5.TFile) {
          this.debouncedAutoSync(file);
        }
      })
    );
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  isPublished(file) {
    var _a;
    const cache = this.app.metadataCache.getFileCache(file);
    const publish = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.publish;
    return publish === true;
  }
  async togglePublish(file) {
    const current = this.isPublished(file);
    const next = !current;
    await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      frontmatter["publish"] = next;
    });
    new import_obsidian5.Notice(`Marked as ${next ? "publish" : "private"}: ${file.basename}`);
    if (next && this.settings.autoSync) {
      this.syncSingleFile(file);
    }
    if (!next) {
      this.deleteFromBlog(file);
    }
  }
  debouncedAutoSync(file) {
    if (!this.settings.autoSync)
      return;
    if (!this.isPublished(file))
      return;
    const key = file.path;
    const existing = this.syncTimers.get(key);
    if (existing)
      clearTimeout(existing);
    this.syncTimers.set(
      key,
      setTimeout(() => {
        this.syncTimers.delete(key);
        this.syncSingleFile(file);
      }, 800)
    );
  }
  async syncSingleFile(file) {
    const blogPath = this.settings.blogFolderPath.trim();
    if (!blogPath) {
      new import_obsidian5.Notice("Blog folder path is not configured. Check plugin settings.");
      return;
    }
    try {
      let content = await this.app.vault.read(file);
      content = ensureTitle(content, file.basename);
      const targetPath = path2.join(
        blogPath.replace(/[/\\]$/, ""),
        file.path
      );
      const targetDir = path2.dirname(targetPath);
      if (!fs3.existsSync(targetDir)) {
        fs3.mkdirSync(targetDir, { recursive: true });
      }
      fs3.writeFileSync(targetPath, content, "utf-8");
      new import_obsidian5.Notice(`Synced to blog: ${file.path}`);
      if (this.settings.autoDeploy)
        this.resetDeployTimer();
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      new import_obsidian5.Notice(`Sync failed: ${file.basename}. ${msg}`);
      console.error("PublishToBlog sync error:", e);
    }
  }
  async syncAllPublished() {
    const blogPath = this.settings.blogFolderPath.trim();
    if (!blogPath) {
      new import_obsidian5.Notice("Blog folder path is not configured. Check plugin settings.");
      return;
    }
    const files = this.app.vault.getMarkdownFiles();
    let synced = 0;
    let errors = 0;
    for (const file of files) {
      if (this.isPublished(file)) {
        try {
          await this.syncSingleFile(file);
          synced++;
        } catch (e) {
          errors++;
        }
      }
    }
    new import_obsidian5.Notice(`Sync complete: ${synced} synced${errors > 0 ? `, ${errors} errors` : ""}`);
  }
  resetDeployTimer() {
    if (this.deployTimer)
      clearTimeout(this.deployTimer);
    this.deployTimer = setTimeout(() => {
      this.deployTimer = null;
      this.runDeploy();
    }, this.settings.bufferMinutes * 60 * 1e3);
  }
  runDeploy() {
    if (this.isDeploying) {
      console.log("PublishToBlog: Deploy already in progress, skipping.");
      return;
    }
    const hexoRoot = this.settings.hexoRootPath.trim();
    const cmd = this.settings.deployCommand.trim();
    if (!hexoRoot || !cmd) {
      new import_obsidian5.Notice("Hexo root path or deploy command not configured. Check plugin settings.");
      return;
    }
    if (!fs3.existsSync(hexoRoot)) {
      new import_obsidian5.Notice(`Hexo root path does not exist: ${hexoRoot}`);
      return;
    }
    this.isDeploying = true;
    new import_obsidian5.Notice(`Deploy started: ${cmd}`);
    (0, import_child_process.exec)(cmd, { cwd: hexoRoot }, (error, stdout, stderr) => {
      this.isDeploying = false;
      if (error) {
        new import_obsidian5.Notice(`Deploy failed: ${error.message}`);
        console.error("PublishToBlog deploy error stdout:", stdout);
        console.error("PublishToBlog deploy error stderr:", stderr);
      } else {
        new import_obsidian5.Notice("Deploy completed successfully!");
        if (stdout)
          console.log("PublishToBlog deploy stdout:", stdout);
      }
    });
  }
  cancelDeployTimer() {
    if (this.deployTimer) {
      clearTimeout(this.deployTimer);
      this.deployTimer = null;
    }
  }
  deleteFromBlog(file) {
    const blogPath = this.settings.blogFolderPath.trim();
    if (!blogPath)
      return;
    const targetPath = path2.join(
      blogPath.replace(/[/\\]$/, ""),
      file.path
    );
    if (!fs3.existsSync(targetPath))
      return;
    try {
      fs3.unlinkSync(targetPath);
      new import_obsidian5.Notice(`Removed from blog: ${file.path}`);
      let dir = path2.dirname(targetPath);
      while (dir !== blogPath.replace(/[/\\]$/, "")) {
        try {
          const remaining = fs3.readdirSync(dir);
          if (remaining.length === 0) {
            fs3.rmdirSync(dir);
            dir = path2.dirname(dir);
          } else {
            break;
          }
        } catch (e) {
          break;
        }
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      new import_obsidian5.Notice(`Failed to remove from blog: ${file.basename}. ${msg}`);
    }
  }
  async activateDashboard() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_DASHBOARD)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({
          type: VIEW_TYPE_DASHBOARD,
          active: true
        });
        leaf = rightLeaf;
      }
    }
    if (leaf)
      workspace.revealLeaf(leaf);
  }
  onunload() {
    this.syncTimers.forEach((t) => clearTimeout(t));
    this.syncTimers.clear();
    if (this.deployTimer)
      clearTimeout(this.deployTimer);
  }
};
function ensureTitle(content, fallbackTitle) {
  if (/^---[\s\S]*?\ntitle:\s*.+/m.test(content))
    return content;
  const fmMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (fmMatch) {
    return content.replace(
      /^---\r?\n/,
      `---
title: "${fallbackTitle.replace(/"/g, '\\"')}"
`
    );
  }
  const date = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
  return `---
title: "${fallbackTitle.replace(/"/g, '\\"')}"
date: ${date}
---

${content}`;
}
